(() => {
  const M=window.Mockup=window.Mockup||{}, C=()=>M.Components, D=()=>M.data, icon=(...a)=>M.icon(...a);
  const stateView=(ctx,e)=>ctx.state&&ctx.state!=='normal'?C().state(ctx.state,e):null;
  M.screens=M.screens||{};
  M.screens.documentsList=(ctx)=>{
    const state=stateView(ctx,'documentos'); if(state)return `${C().pageHeader('Documentos','',{label:'Generar documento',href:'/backoffice/documentos?modal=generate'})}${state}`;
    let html=`${C().pageHeader('Documentos','Localiza, genera y descarga documentos del sistema.',{label:'Generar documento',href:'/backoffice/documentos?modal=generate'})}${C().filters([{label:'Dominio',options:['Todos','scheduling','academic','monitoring']},{label:'Estado',options:['Todos','Disponible','Generando','Archivado','Error de generación']},{label:'Plantilla',type:'search',placeholder:'Código de plantilla'},{label:'Fecha',type:'date'}])}${C().table([{label:'Título',render:r=>`<a href="#/backoffice/documentos/${r.id}"><strong>${r.title}</strong></a>`},{label:'Plantilla',key:'template'},{label:'Dominio',key:'domain'},{label:'Estado',render:r=>C().status(r.status)},{label:'Versión',key:'version'},{label:'Creado',key:'created'},{label:'Acción',render:r=>r.status==='AVAILABLE'?'<button class="btn btn-secondary btn-sm">Descargar</button>':r.status==='GENERATION_FAILED'?'<button class="btn btn-danger-subtle btn-sm">Reintentar</button>':'<button class="btn btn-secondary btn-sm" disabled>Descargar</button>'}],D().documents,{caption:'Documentos',total:42,start:1,end:4,pageSize:10})}`;
    if(ctx.query.get('modal')==='generate') html+=generateModal();
    return html;
  };
  function generateModal(){ return C().modal('Generar documento',`<div class="form-grid"><div class="form-field full"><label>Plantilla</label><select><option>CONSTANCIA_HORARIO — Constancia de horario</option><option>REPORTE_CONFLICTOS — Reporte de conflictos</option></select></div><div class="form-field"><label>Dominio</label><select><option>Horario</option><option>Ficha</option><option>Constancia</option><option>Actor</option><option>Reporte</option></select></div><div class="form-field"><label>Servicio propietario</label><input value="scheduling-service"></div><div class="form-field full"><label>Entidad propietaria (UUID)</label><input value="sch-01"><div class="field-error">${icon('warning')}Ingresa un UUID válido.</div></div><div class="form-field full"><label>Título</label><input value="Constancia de horario — Ficha 2874412"></div><div class="form-field full"><label>Datos (JSON opcional)</label><textarea class="code-view" style="color:#e4e7ec" placeholder='{"ficha_number":"2874412"}'></textarea></div></div>`,`<button class="btn btn-secondary" data-close-modal>Cancelar</button><button class="btn btn-primary">Generar</button>`); }
  M.screens.templatesList=(ctx)=>{
    const state=stateView(ctx,'plantillas'); if(state)return `${C().pageHeader('Plantillas de documento','',{label:'+ Nueva plantilla',href:'/backoffice/documentos/plantillas/nueva/editar'})}${state}`;
    return `${C().pageHeader('Plantillas de documento','Catálogo usado por el generador de documentos.',{label:'+ Nueva plantilla',href:'/backoffice/documentos/plantillas/tpl-01/editar'})}${C().filters([{label:'Tipo de salida',options:['Todos','PDF','Excel','Word']},{label:'Código',type:'search',placeholder:'Buscar código'},{label:'Activa',options:['Todas','Sí','No']}])}${C().table([{label:'Código',render:r=>`<a href="#/backoffice/documentos/plantillas/${r.id}/editar"><strong>${r.code}</strong></a>`},{label:'Nombre',key:'name'},{label:'Tipo de salida',key:'output'},{label:'Versión',key:'version'},{label:'Activa',render:r=>C().status(r.active?'ACTIVE':'INACTIVE')},{label:'Actualizada',key:'updated'}],D().templates,{caption:'Plantillas',total:18,start:1,end:4,pageSize:10})}`;
  };
  M.screens.documentDetail=(ctx)=>{
    const state=stateView(ctx,'documento'); if(state)return `${C().pageHeader('Detalle de documento','',null,{label:'Volver a Documentos',href:'/backoffice/documentos'})}${state}`;
    const d=D().documents.find(x=>x.id===ctx.params[0])||D().documents[0];
    const versions=[{version:'3 · Vigente',author:'Ana Torres',date:'06/08/2026, 09:20',notes:'Ajuste de encabezado institucional.'},{version:'2',author:'Ana Torres',date:'05/08/2026, 16:15',notes:'Corrección de datos de ficha.'},{version:'1',author:'Sistema',date:'04/08/2026, 10:02',notes:'Versión inicial.'}];
    return `${C().pageHeader(d.title,'',null,{label:'Volver a Documentos',href:'/backoffice/documentos'})}<section class="panel"><header class="panel-header"><div><h2 class="panel-title">${d.title}</h2><p class="panel-subtitle">${d.template}</p></div>${C().status(d.status)}</header><div class="panel-body">${C().details([['Dominio',d.domain],['Servicio propietario','document-service'],['Entidad propietaria',`${d.owner} ${icon('copy')}`],['Tipo MIME','application/pdf'],['Tamaño','842 KB'],['Autor','Ana Torres'],['Creado',d.created],['Última actualización','06/08/2026, 09:20']])}<div class="form-actions"><button class="btn btn-primary" ${d.status!=='AVAILABLE'?'disabled title="Este documento aún no está disponible para descargar"':''}>${icon('download')}Descargar versión vigente</button></div></div></section><section class="panel" style="margin-top:20px"><header class="panel-header"><div><h2 class="panel-title">Versiones</h2></div></header>${C().table([{label:'N.º de versión',key:'version'},{label:'Autor',key:'author'},{label:'Fecha',key:'date'},{label:'Notas',key:'notes'}],versions,{caption:'Versiones del documento',pagination:false})}<footer class="panel-footer"><small>La ruta de almacenamiento nunca se expone. La descarga usa una URL firmada temporal.</small></footer></section>`;
  };
  M.screens.templateEditor=(ctx)=>{
    const state=stateView(ctx,'plantilla'); if(state)return `${C().pageHeader('Editor de plantilla','',null,{label:'Volver a Plantillas',href:'/backoffice/documentos/plantillas'})}${state}`;
    const preview=ctx.query.get('preview')==='1';
    let html=`${C().pageHeader('Editor de plantilla de documento','Versión actual: 3',null,{label:'Volver a Plantillas',href:'/backoffice/documentos/plantillas'})}<section class="panel"><div class="panel-body"><div class="form-grid"><div class="form-field"><label>Código</label><input value="CONSTANCIA_HORARIO" readonly title="El código no puede cambiar en edición"></div><div class="form-field"><label>Nombre</label><input value="Constancia de horario"></div><div class="form-field"><label>Tipo de salida</label><select><option>PDF</option><option>Excel</option><option>Word</option></select></div><label class="form-field" style="display:flex;grid-template-columns:auto 1fr;align-items:center"><input type="checkbox" checked style="width:20px;min-height:20px">Activa</label><div class="form-field full"><label>Cuerpo HTML / Handlebars</label><textarea class="editor-area"><!doctype html>
<html>
  <body>
    <h1>Constancia de horario</h1>
    <p>Ficha: {{ficha_number}}</p>
    <p>Período: {{period}}</p>
  </body>
</html></textarea></div></div></div></section><div class="sticky-actions"><a class="btn btn-secondary" href="#/backoffice/documentos/plantillas/tpl-01/editar?preview=1">Previsualizar</a><button class="btn btn-primary">Guardar</button></div>`;
    if(preview) html+=C().modal('Previsualizar plantilla',`<div class="editor-grid"><section><div class="form-field"><label>Datos de muestra</label><textarea class="editor-area" style="min-height:300px">{
  "ficha_number": "2874412",
  "period": "2026-2"
}</textarea></div><button class="btn btn-primary" style="margin-top:12px">Renderizar</button></section><section><h3>Vista previa</h3><div class="preview-frame"><h1>Constancia de horario</h1><p>Ficha: 2874412</p><p>Período: 2026-2</p></div><div class="alert alert-warning" style="margin-top:12px">${icon('warning')}Placeholders sin valor: instructor_name</div></section></div>`,`<button class="btn btn-secondary" data-close-modal>Cerrar</button>`,'modal-lg');
    return html;
  };
})();
