(() => {
  const M=window.Mockup=window.Mockup||{}, D=()=>M.data, icon=(...a)=>M.icon(...a);
  M.homeForRole=(role)=>({coordinator:'/',instructor:'/instructor/mi-horario',learner:'/mi-horario',director:'/admin/indicadores',support:'/backoffice/documentos'}[role]||'/login');
  M.renderShell=(ctx,content)=>{
    const user=D().userByRole[ctx.role]||D().userByRole.coordinator;
    const nav=M.navByRole[ctx.role]||[];
    const path=ctx.path;
    const overlay=ctx.query.get('overlay');
    return `<div class="app-shell"><a class="skip-link" href="#main-content">Saltar al contenido</a><header class="topbar"><div class="topbar-start"><button class="icon-btn" data-mobile-nav aria-label="Abrir navegación">${icon('menu')}</button><button class="icon-btn desktop-collapse" data-collapse-nav aria-label="Colapsar navegación">${icon('collapse')}</button><a class="brand" href="#${M.homeForRole(ctx.role)}"><span class="brand-mark">SENA</span><span class="brand-copy"><strong>SENA — Gestión de Horarios</strong><span>Centro de Formación</span></span></a></div><div class="topbar-end"><button class="icon-btn" data-notifications aria-label="Notificaciones, 3 pendientes">${icon('bell')}<span class="notification-badge">3</span></button><div class="user-menu-wrap"><button class="user-trigger" data-user-trigger aria-expanded="false"><span class="user-avatar">${user.initials}</span><span class="user-copy"><strong>${user.name}</strong><span>${user.label}</span></span>${icon('chevronDown')}</button><div class="dropdown" data-user-menu hidden><div style="padding:10px 12px"><strong>${user.name}</strong><div style="font-size:12px;color:var(--color-text-muted)">${user.label}</div></div><div class="dropdown-separator"></div><div class="role-switch"><small>Modo revisión · Cambiar rol</small>${Object.entries(D().userByRole).map(([r,u])=>`<button class="dropdown-item" data-switch-role="${r}">${r===ctx.role?'✓ ':''}${u.label}</button>`).join('')}</div><div class="dropdown-separator"></div><a class="dropdown-item" href="#/inventory">${icon('folder')}Índice de 45 pantallas</a><a class="dropdown-item" href="#/login">${icon('logout')}Cerrar sesión</a></div></div></div></header><aside class="sidebar" aria-label="Navegación principal"><p class="sidebar-label">${user.label}</p><nav class="nav">${nav.map(([label,href,ico])=>`<a class="nav-link ${isActive(path,href)?'active':''}" href="#${href}">${icon(ico)}<span>${label}</span></a>`).join('')}</nav></aside><button class="sidebar-backdrop" data-nav-backdrop aria-label="Cerrar navegación"></button><div class="main-area">${ctx.offline?`<div class="alert alert-warning offline-banner">${icon('wifiOff')}<strong>Sin conexión</strong> — mostrando datos guardados</div>`:''}<main class="content" id="main-content">${content}</main></div>${overlay==='notifications'?notificationPanel():''}</div>`;
  };
  function isActive(path,href){ if(href==='/')return path==='/';return path===href||path.startsWith(href+'/'); }
  function notificationPanel(){
    return `<aside class="notification-panel" role="dialog" aria-label="Panel de notificaciones"><header class="panel-header"><div><h2 class="panel-title">Notificaciones</h2><p class="panel-subtitle">Últimos 5 avisos</p></div><button class="icon-btn" data-close-notifications>${icon('x')}</button></header><div>${D().notifications.slice(0,5).map(n=>`<article class="notification-item"><span class="conflict-icon" style="width:36px;height:36px;background:var(--color-brand-soft);color:var(--color-brand)">${icon('bell')}</span><div><h3>${n.subject}</h3><p>${n.summary}</p><time>${n.date}</time></div>${M.Components.status(n.status)}</article>`).join('')}</div><footer class="panel-footer"><a class="btn btn-secondary" style="width:100%" href="#/notificaciones?as=learner">Ver todas</a></footer></aside>`;
  }
})();
