(() => {
  const M = window.Mockup = window.Mockup || {};
  const roles = {
    coordinator: ['coordinator','director'], instructor:['instructor'], learner:['learner'], director:['director'], support:['support']
  };
  M.inventory = [
    {n:1,group:'01 · Auth y shell',name:'Login',route:'/login',role:'public',mfe:'iam'},
    {n:2,group:'01 · Auth y shell',name:'Recuperar contraseña',route:'/forgot-password',role:'public',mfe:'iam'},
    {n:3,group:'01 · Auth y shell',name:'Nueva contraseña',route:'/reset-password',role:'public',mfe:'iam'},
    {n:4,group:'01 · Auth y shell',name:'App Shell por rol',route:'/review/app-shell',role:'coordinator',mfe:'shell'},
    {n:5,group:'01 · Auth y shell',name:'Panel de notificaciones',route:'/review/app-shell?overlay=notifications',role:'coordinator',mfe:'shell'},
    {n:6,group:'01 · Auth y shell',name:'Estados globales',route:'/system-states',role:'coordinator',mfe:'shell'},
    {n:7,group:'02 · Coordinador',name:'Dashboard / Inicio',route:'/',role:'coordinator',mfe:'shell + scheduling + academic'},
    {n:8,group:'02 · Coordinador',name:'Horarios — lista',route:'/horarios',role:'coordinator',mfe:'scheduling'},
    {n:9,group:'02 · Coordinador',name:'Detalle de horario',route:'/horarios/sch-03',role:'coordinator',mfe:'scheduling'},
    {n:10,group:'02 · Coordinador',name:'Crear / editar horario',route:'/horarios/nuevo',role:'coordinator',mfe:'scheduling'},
    {n:11,group:'02 · Coordinador',name:'Modal agregar / editar sesión',route:'/horarios/sch-01?modal=session',role:'coordinator',mfe:'scheduling'},
    {n:12,group:'02 · Coordinador',name:'Modal confirmar publicación',route:'/horarios/sch-02?modal=publish',role:'coordinator',mfe:'scheduling'},
    {n:13,group:'02 · Coordinador',name:'Panel de conflictos',route:'/horarios/sch-02/conflictos',role:'coordinator',mfe:'scheduling'},
    {n:14,group:'02 · Coordinador',name:'Modal resolver conflicto',route:'/horarios/sch-02/conflictos?modal=resolve',role:'coordinator',mfe:'scheduling'},
    {n:15,group:'02 · Coordinador',name:'Disponibilidad',route:'/disponibilidad',role:'coordinator',mfe:'environment + actors'},
    {n:16,group:'02 · Coordinador',name:'Detalle de ambiente',route:'/disponibilidad/ambientes/env-01',role:'coordinator',mfe:'environment'},
    {n:17,group:'02 · Coordinador',name:'Fichas — lista',route:'/fichas',role:'coordinator',mfe:'academic'},
    {n:18,group:'02 · Coordinador',name:'Detalle de ficha',route:'/fichas/fic-01',role:'coordinator',mfe:'academic'},
    {n:19,group:'03 · Instructor',name:'Mi horario — semana',route:'/instructor/mi-horario',role:'instructor',mfe:'scheduling'},
    {n:20,group:'03 · Instructor',name:'Detalle de sesión',route:'/instructor/mi-horario?panel=session',role:'instructor',mfe:'scheduling'},
    {n:21,group:'03 · Instructor',name:'Mi disponibilidad',route:'/instructor/mi-disponibilidad',role:'instructor',mfe:'actors'},
    {n:22,group:'03 · Instructor',name:'Modal crear excepción',route:'/instructor/mi-disponibilidad?modal=exception',role:'instructor',mfe:'actors'},
    {n:23,group:'03 · Instructor',name:'Seguimiento de ficha',route:'/instructor/seguimiento',role:'instructor',mfe:'monitoring'},
    {n:24,group:'03 · Instructor',name:'Registrar seguimiento',route:'/instructor/seguimiento?modal=tracking',role:'instructor',mfe:'monitoring'},
    {n:25,group:'04 · Aprendiz',name:'Mi horario — semana',route:'/mi-horario',role:'learner',mfe:'scheduling'},
    {n:26,group:'04 · Aprendiz',name:'Notificaciones',route:'/notificaciones',role:'learner',mfe:'monitoring'},
    {n:27,group:'04 · Aprendiz',name:'Detalle de clase',route:'/mi-horario/sesiones/ses-01',role:'learner',mfe:'scheduling'},
    {n:28,group:'04 · Aprendiz',name:'Detalle de notificación',route:'/notificaciones/not-01',role:'learner',mfe:'monitoring'},
    {n:29,group:'05 · Administrador',name:'Panel de indicadores',route:'/admin/indicadores',role:'director',mfe:'monitoring'},
    {n:30,group:'05 · Administrador',name:'Drill-down de KPI',route:'/admin/indicadores/track-01/attendance',role:'director',mfe:'monitoring'},
    {n:31,group:'05 · Administrador',name:'Usuarios — lista',route:'/admin/usuarios',role:'director',mfe:'iam'},
    {n:32,group:'05 · Administrador',name:'Crear / editar usuario',route:'/admin/usuarios?modal=user',role:'director',mfe:'iam'},
    {n:33,group:'05 · Administrador',name:'Detalle de usuario',route:'/admin/usuarios/usr-02',role:'director',mfe:'iam'},
    {n:34,group:'05 · Administrador',name:'Modal asignar / revocar rol',route:'/admin/usuarios/usr-02?modal=role',role:'director',mfe:'iam'},
    {n:35,group:'05 · Administrador',name:'Datos de referencia',route:'/admin/datos-referencia',role:'director',mfe:'reference'},
    {n:36,group:'05 · Administrador',name:'Editar catálogo / valor / parámetro',route:'/admin/datos-referencia?modal=reference',role:'director',mfe:'reference'},
    {n:37,group:'06 · Back-office',name:'Documentos — lista',route:'/backoffice/documentos',role:'support',mfe:'document'},
    {n:38,group:'06 · Back-office',name:'Plantillas de documento',route:'/backoffice/documentos/plantillas',role:'support',mfe:'document'},
    {n:39,group:'06 · Back-office',name:'Auditoría',route:'/backoffice/auditoria',role:'support',mfe:'audit'},
    {n:40,group:'06 · Back-office',name:'Parametrización / catálogos',route:'/backoffice/parametrizacion',role:'support',mfe:'reference'},
    {n:41,group:'06 · Back-office',name:'Detalle de documento + versiones',route:'/backoffice/documentos/doc-01',role:'support',mfe:'document'},
    {n:42,group:'06 · Back-office',name:'Modal generar documento',route:'/backoffice/documentos?modal=generate',role:'support',mfe:'document'},
    {n:43,group:'06 · Back-office',name:'Editor / preview de plantilla',route:'/backoffice/documentos/plantillas/tpl-01/editar',role:'support',mfe:'document'},
    {n:44,group:'06 · Back-office',name:'Modal detalle de auditoría',route:'/backoffice/auditoria?modal=audit',role:'support',mfe:'audit'},
    {n:45,group:'06 · Back-office',name:'CRUD catálogo / valor / parámetro',route:'/backoffice/parametrizacion?modal=crud',role:'support',mfe:'reference'},
    {n:46,group:'07 · Parametrización',name:'Hub de parametrización',route:'/admin/parametrizacion',role:'director',mfe:'reference'},
    {n:47,group:'07 · Parametrización',name:'Currículo académico',route:'/admin/parametrizacion/curriculo',role:'director',mfe:'academic'},
    {n:48,group:'07 · Parametrización',name:'Jornadas / franjas horarias',route:'/admin/parametrizacion/jornadas',role:'director',mfe:'scheduling'},
    {n:49,group:'07 · Parametrización',name:'Tipos de ambiente e inventario',route:'/admin/parametrizacion/ambientes',role:'director',mfe:'environment'},
    {n:50,group:'07 · Parametrización',name:'Catálogos de monitoreo (KPI/alertas)',route:'/admin/parametrizacion/monitoreo',role:'director',mfe:'monitoring'},
    {n:51,group:'07 · Parametrización',name:'Estados de actores',route:'/admin/parametrizacion/estados',role:'director',mfe:'actors'},
    {n:52,group:'07 · Parametrización',name:'Geografía institucional',route:'/admin/parametrizacion/geografia',role:'director',mfe:'reference'},
    {n:53,group:'07 · Parametrización',name:'RBAC — roles y permisos',route:'/admin/parametrizacion/rbac',role:'director',mfe:'iam'}
  ];
  M.routeDefinitions = [
    {pattern:/^\/login$/,public:true,screen:'login'},
    {pattern:/^\/forgot-password$/,public:true,screen:'forgotPassword'},
    {pattern:/^\/reset-password$/,public:true,screen:'resetPassword'},
    {pattern:/^\/inventory$/,public:true,screen:'inventory'},
    {pattern:/^\/review\/app-shell$/,roles:['coordinator','instructor','learner','director','support'],screen:'appShellReview'},
    {pattern:/^\/system-states$/,roles:['coordinator','instructor','learner','director','support'],screen:'systemStates'},
    {pattern:/^\/$/,roles:['coordinator'],screen:'coordinatorDashboard'},
    {pattern:/^\/horarios$/,roles:['coordinator','director'],screen:'schedulesList'},
    {pattern:/^\/horarios\/nuevo$/,roles:['coordinator'],screen:'scheduleEditor'},
    {pattern:/^\/horarios\/([^/]+)\/conflictos$/,roles:['coordinator','director'],screen:'conflictsPanel'},
    {pattern:/^\/horarios\/([^/]+)$/,roles:['coordinator','director'],screen:'scheduleResource'},
    {pattern:/^\/disponibilidad$/,roles:['coordinator','director'],screen:'availability'},
    {pattern:/^\/disponibilidad\/ambientes\/([^/]+)$/,roles:['coordinator','director'],screen:'environmentDetail'},
    {pattern:/^\/fichas$/,roles:['coordinator','director'],screen:'fichasList'},
    {pattern:/^\/fichas\/([^/]+)$/,roles:['coordinator','director'],screen:'fichaDetail'},
    {pattern:/^\/instructor\/mi-horario$/,roles:['instructor'],screen:'instructorSchedule'},
    {pattern:/^\/instructor\/mi-disponibilidad$/,roles:['instructor'],screen:'instructorAvailability'},
    {pattern:/^\/instructor\/seguimiento$/,roles:['instructor'],screen:'tracking'},
    {pattern:/^\/mi-horario$/,roles:['learner'],screen:'learnerSchedule'},
    {pattern:/^\/mi-horario\/sesiones\/([^/]+)$/,roles:['learner'],screen:'learnerClassDetail'},
    {pattern:/^\/notificaciones$/,roles:['learner'],screen:'notificationsList'},
    {pattern:/^\/notificaciones\/([^/]+)$/,roles:['learner'],screen:'notificationDetail'},
    {pattern:/^\/admin\/indicadores$/,roles:['director'],screen:'kpiDashboard'},
    {pattern:/^\/admin\/indicadores\/([^/]+)\/([^/]+)$/,roles:['director'],screen:'kpiDrilldown'},
    {pattern:/^\/admin\/usuarios$/,roles:['director','support'],screen:'usersList'},
    {pattern:/^\/admin\/usuarios\/([^/]+)$/,roles:['director','support'],screen:'userDetail'},
    {pattern:/^\/admin\/datos-referencia$/,roles:['director','support'],screen:'adminReference'},
    {pattern:/^\/backoffice\/documentos$/,roles:['support'],screen:'documentsList'},
    {pattern:/^\/backoffice\/documentos\/plantillas$/,roles:['support'],screen:'templatesList'},
    {pattern:/^\/backoffice\/documentos\/plantillas\/([^/]+)\/editar$/,roles:['support'],screen:'templateEditor'},
    {pattern:/^\/backoffice\/documentos\/([^/]+)$/,roles:['support'],screen:'documentDetail'},
    {pattern:/^\/backoffice\/auditoria$/,roles:['support'],screen:'auditList'},
    {pattern:/^\/backoffice\/parametrizacion$/,roles:['support'],screen:'parametersList'},
    {pattern:/^\/admin\/parametrizacion$/,roles:['director','support'],screen:'paramHub'},
    {pattern:/^\/admin\/parametrizacion\/curriculo$/,roles:['director','support'],screen:'paramCurriculum'},
    {pattern:/^\/admin\/parametrizacion\/jornadas$/,roles:['director','support'],screen:'paramTimeSlots'},
    {pattern:/^\/admin\/parametrizacion\/ambientes$/,roles:['director','support'],screen:'paramEnvironmentTypes'},
    {pattern:/^\/admin\/parametrizacion\/monitoreo$/,roles:['director','support'],screen:'paramMonitoring'},
    {pattern:/^\/admin\/parametrizacion\/estados$/,roles:['director','support'],screen:'paramActorStatus'},
    {pattern:/^\/admin\/parametrizacion\/geografia$/,roles:['director','support'],screen:'paramGeography'},
    {pattern:/^\/admin\/parametrizacion\/rbac$/,roles:['director','support'],screen:'paramRbac'}
  ];
  M.navByRole = {
    coordinator:[['Inicio','/','home'],['Horarios','/horarios','calendar'],['Disponibilidad','/disponibilidad','clock'],['Fichas','/fichas','folder']],
    instructor:[['Mi horario','/instructor/mi-horario','calendar'],['Mi disponibilidad','/instructor/mi-disponibilidad','clock'],['Seguimiento','/instructor/seguimiento','activity']],
    learner:[['Mi horario','/mi-horario','calendar'],['Notificaciones','/notificaciones','bell']],
    director:[['Indicadores','/admin/indicadores','chart'],['Usuarios','/admin/usuarios','users'],['Datos de referencia','/admin/datos-referencia','file'],['Parametrización','/admin/parametrizacion','settings']],
    support:[['Documentos','/backoffice/documentos','file'],['Plantillas','/backoffice/documentos/plantillas','edit'],['Auditoría','/backoffice/auditoria','activity'],['Parametrización','/admin/parametrizacion','settings']]
  };
})();
